---
- hosts: all
  become: yes

  tasks:

    - name: create docker image using war file
      command: docker build -t devops-image:latest .
      args:
        chdir: /opt/docker

    - name: create tag to image
      command: docker tag devops-image devendra999/devops-image

    - name: push image on to dockerhub
      command: docker push devendra999/devops-image

    - name: remove docker images from ansible server
      command: docker rmi tomcat devops-image:latest devendra999/devops-image
      ignore_errors: yes
