
---
- hosts: all
  become: yes

  tasks:

    - name: stop current running container
      command: docker stop devops-container
      ignore_errors: yes

    - name: remove stopped docker container
      command: docker rm devops-container
      ignore_errors: yes

    - name: remove current docker image
      command: docker rmi devendra999/devops-image:latest
      ignore_errors: yes

    - name: pull docker image from dockerhub
      command: docker pull devendra999/devops-image:latest

    - name: creating docker container using devops-image
      command: docker run -d --name devops-container -p 8080:8080 devendra999/devops-image:latest
